import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { StoreProvider } from "@/redux/StoreProvider";
import ClientPreloader from "@/components/common/ClientPreloader";
import { VideoUploadProvider } from "@/contexts/VideoUploadContext";
import VideoUploadIndicator from "@/components/common/VideoUploadIndicator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "OLD CLUB MAN - Network, Community",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <VideoUploadProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ClientPreloader />
            <Toaster position="top-right" reverseOrder={false} />
            <VideoUploadIndicator />
            {children}
          </body>
        </html>
      </VideoUploadProvider>
    </StoreProvider>
  );
}
